version: 2
jobs:
  build-and-push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GCP_CREDS} > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1

  deploy-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GCP_CREDS} > ${HOME}/gcp-key.json
      - run: export IMAGE=eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}
      - run: export VERSION=${CIRCLE_SHA1:latest}
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run: gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone="${CLUSTER_REGION}"
      - run: cat k8s/*.yaml | envsubst | kubectl apply -f -

workflows:
  version: 2
  build-and-deploy-image:
    jobs:
      - build-and-push-image
      - deploy-image:
          requires:gst
            - build-and-push-image