version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./scripts/build.sh
  deploy:
    machine: true
    steps:
      - checkout
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
