---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-crt
spec:
  commonName: "demoapplication.squadzero.io"
  dnsNames:
    - "demoapplication.squadzero.io"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-demo
  secretName: demo-crt
