---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: demo-crt
spec:
  commonName: "testmynewapplication.tk"
  dnsNames:
    - "testmynewapplication.tk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-demo
  secretName: demo-crt
