---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: default
  labels:
    app: demo-application
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-demo
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demoapplication.squadzero.io
      http:
        paths:
          - backend:
              serviceName: demo-application
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - demoapplication.squadzero.io
      secretName: demo-crt
