---
apiVersion: v1
kind: Service
metadata:
  name: demo-application
  namespace: default
  labels:
    app: demo-application
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: http
  selector:
    app: demo-application
